### ISSUE TITLE
Todo: Create a hello world react app in typescript

### ISSUE THREAD

**Issue by DuskyElf** [DuskyElf/elfmsg#12]
Create a hello world react app in typescript in a new directory named `web`.
There needs to be react routes setup, where `root` route shows `Hello World!`

Note it should be a simple react app, ie. there only lives `index.tsx` in the `web/src` directory.

**Comment by DrSwaggos** [comment]
I would like to do this. Is there anything I have to know in addition to:

- create a new react app 
- it must contain react routes
- the root route should respond with "Hello World!"
- it should be as simple as index.tsx in web/src

**Comment by DuskyElf** [comment]
Perfect! @DrSwaggos , Thanks for your reply.
