### ISSUE TITLE
Todo: Design auth pages, ie. sign up and login.

### ISSUE THREAD

**Issue by DuskyElf** [DuskyElf/elfmsg#15]
# Design auth pages, ie. sign up and login.

## Instructions overview -
- Create `auth` directory as a sub-directory of `web`, where all the `auth` related code would go.
- Register a router namespace `auth` in `web/index.tsx`.
- There should be different files routing to `auth/sign-up` and `auth/login` respectively.
- But a single `web/auth/auth-style.css` which would be imported in both the pages.

Even if you don't know typescript or React, you could still contribute for the styling.

## Styling
The style of the pages isn't well planned. Just that it should be dark themed.

**Comment by cj-praveen** [comment]
@DuskyElf Hey, I'm interested to contribute in styling part.

**Comment by DuskyElf** [comment]
Sure @cj-praveen , We appreciate all kinds of contributions. I'm working on creating the pages in typescript as stated above, then you could pull this branch (ie. issue-#15) and make design changes.

**Comment by DuskyElf** [comment]
Implemented the workflow to design the auth pages - https://github.com/DuskyElf/elfmsg/commit/848733b64530024f54dec4500b55e26cf6b06cb5
@cj-praveen You could start working on the style.

Instructions -
- CSS for auth pages goes in `web/auth/auth-style.css`
- `login.tsx` and `sign-up.tsx` contains root components for login and sign-up respectively.
- Could just put the plain `HTML` inside those components in React form (`class` -> `className` be one difference).

**Comment by DuskyElf** [comment]
Check #27
